### ISSUE TITLE
Should Axios and Vuetify be dependencies, rather than devDependencies?

### ISSUE THREAD

**Issue by mcquiggd** [ErikCH/NuxtiTunesSearch#1]
As per the subject title. 

I am presuming as Nuxt is performing the SSR, they do not need to be packaged and sent to the client. 

It would be really useful (reassuring!) to get clarification if this is correct - this is the first project I have seen that places them as devDependencies.

**Comment by mcquiggd** [comment]
Ah, I see they are subsequently included in the vendor bundle. 

Not seen that combination of devDepencies and vendor bundle before.

**Comment by ErikCH** [comment]
Oops! You are right. Send a PR and I'll merge it. Otherwise I'l ll fix it later.

**Comment by mcquiggd** [comment]
Looking at it, you also don't need Axios in the Vendor bundle - it's only used on the server. 

Also, you shouldn't need to explicitly add Vuetify, as with Nuxt defaulting to Universal mode for rendering, WebPack will add that to the Vendor bundle itself...

Correct..? :-)

**Comment by ErikCH** [comment]
@mcquiggd from the research I read, you add it to the vendor file so that way it gets added to the application bundle. Otherwise it gets duplicated every time you import it in. It's recommended in the official documentation. https://nuxtjs.org/api/configuration-build/#vendor

I could be wrong though, do you have some more information on the internals of how vendor works?

**Comment by mcquiggd** [comment]
I removed Axios from the vendor bundle - and everything functions correctly _in development mode_.

Well, w.r.t Vuetify, I believe as you have explicitly created the Vuetify plugin and 'Vue.used' it, it should be included.

Edit: Just checked _in development mode_ - and it does include Vuetify in the vendor bundle, even when it is not specified in nuxt.config.

Haven't checked a production build and deployment yet.

To be honest, it's better to ask the Nuxt team. I'll post an issue there, and reference this.

**Comment by mcquiggd** [comment]
Actually there is a discussion of this [here](https://github.com/nuxt/nuxt.js/issues/2394) from three weeks ago.

The comment [here](https://github.com/nuxt/nuxt.js/issues/2394#issuecomment-351822091) from a team member is interesting, and explains the behaviour... emphasis mine.

> Yes actually the reason is that _we strictly move every lib (inside node_modules) into vendor chunk_. Until now and in recent RCs strategy was to not do this if it was used in less than 1/2 of the pages. But it seemed something unreasonable for _plugins which by design are included once_. Actually, until now some of those libs were wrongly included in app chunk which just hides the warn but in practice prevents long-term caching. BTW we are always open for ideas and comments if we can improve the approach.

> Off  topic: _We may plan for adding async plugins support, which will be moved to a separate chunk._
